name: Integration Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'  # Run daily at midnight UTC

jobs:
  integration-tests:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew

    - name: Build with Gradle
      run: ./gradlew build -x test

    - name: Run Integration Tests
      run: ./gradlew :coffee-shop-integration-tests:integrationTest

    - name: Upload Test Reports
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: integration-test-reports
        path: |
          coffee-shop-integration-tests/build/reports/tests/integrationTest/
          coffee-shop-integration-tests/build/test-results/integrationTest/
